# Generated by Django 6.0.2 on 2026-02-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='report_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
