# Generated by Django 6.0.2 on 2026-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='exam_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='modality',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='radiologist',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='service_status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='logout_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
